import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={inter.className}>
        <nav className={styles.nav}>
          <ul>
            <li><Link href={'/'}>Main page</Link></li>
            <li>First</li>
            <li>Second</li>
            <li><Link href={'/about'}>Third</Link></li>
            <li><Link href={'/products/typescript'}>Typescript</Link></li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
